"""Added forum models

Revision ID: faf028acdc3e
Revises: c809c3b9f9aa
Create Date: 2025-03-22 21:14:41.351084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf028acdc3e'
down_revision: Union[str, None] = 'c809c3b9f9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('replies_created_by_fkey', 'replies', type_='foreignkey')
    op.create_foreign_key(None, 'replies', 'users', ['user_id'], ['id'])
    op.drop_column('replies', 'created_by')
    op.drop_column('replies', 'is_moderated')
    op.add_column('threads', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('threads_created_by_fkey', 'threads', type_='foreignkey')
    op.create_foreign_key(None, 'threads', 'users', ['user_id'], ['id'])
    op.drop_column('threads', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'threads', type_='foreignkey')
    op.create_foreign_key('threads_created_by_fkey', 'threads', 'users', ['created_by'], ['id'])
    op.drop_column('threads', 'user_id')
    op.add_column('replies', sa.Column('is_moderated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('replies', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.create_foreign_key('replies_created_by_fkey', 'replies', 'users', ['created_by'], ['id'])
    op.drop_column('replies', 'user_id')
    # ### end Alembic commands ###
